api_credentials:
  api_login:
    ZALIAEVIA
  api_passwd:
    2CqV1zyJ
  token_entry_point: https://b2b.alfastrah.ru
  api_entry_point: https://b2b.alfastrah.ru
#  api_passwd:
#    3cYuP9Dg
#  token_entry_point: https://b2b-test2.alfastrah.ru
#  api_entry_point: https://b2b-test2.alfastrah.ru

