api_credentials:
  consumer_key:
    6AaGcdQl2sRzGrYX9Ddg1FLjYb8a
  consumer_secret:
    jiufya85xUUs8LsxtwUZllRTTJAa
  token_entry_point: https://apigateway.renins.com
  api_entry_point: https://apigateway.renins.com/IpotekaAllBanksAPI/1.0.0