api_credentials:
  consumer_key:
    XaL5z9zEq6O_wri6Wb6KbuCS6nAa
  consumer_secret:
    LsX0ALAg0pl6SfsUfoZ5Tka7Qxka
  token_entry_point: https://apigateway.renins.com
  api_entry_point: https://apigateway.renins.com/IpotekaAPI/1.0.0