api_credentials:
  api_login:
    ZaliaevI
  api_passwd:
    '!Mazda002Y'
#  token_entry_point: https://preprodrgs.jarvis.su/PO.Insurance/services/partner
#  api_entry_point: https://preprodrgs.jarvis.su/PO.Insurance/services/partner
  token_entry_point: https://rgs.jarvis.su/PO.Insurance/services/partner
  api_entry_point: https://rgs.jarvis.su/PO.Insurance/services/partner
