dadata_api:
  api_key: '791d0a769029bad14dfac42e10dd27c8d43b5ab4'


velhron_dadata:
  token: '791d0a769029bad14dfac42e10dd27c8d43b5ab4'
  secret: 'f69e957f6b3082f60fb0fb96cc55101253746398'
  # Если у вас инфраструктура состоит из n-сервисов, которые обращаются в dadata, то для контроля запросов в dadata
  # в одной точке, Вам возможно потребуется прокси-кеш. Для замены оригинальных url от dadata на Ваш прокси, можете
  # заполнить следующие необязательные параметры
  #base_general_url: 'https://proxy_dadata.ru/proxy/v2'
  #base_cleaner_url: 'https://cleaner.proxy_dadata.ru/proxy/v1/clean'
  #base_suggestions_url: 'https://suggestions.proxy_dadata.ru/suggestions/proxy/4_1/rs'